package com.opencode.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppphotoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppphotoAllPropertiesEquals(Appphoto expected, Appphoto actual) {
        assertAppphotoAutoGeneratedPropertiesEquals(expected, actual);
        assertAppphotoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppphotoAllUpdatablePropertiesEquals(Appphoto expected, Appphoto actual) {
        assertAppphotoUpdatableFieldsEquals(expected, actual);
        assertAppphotoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppphotoAutoGeneratedPropertiesEquals(Appphoto expected, Appphoto actual) {
        assertThat(actual)
            .as("Verify Appphoto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppphotoUpdatableFieldsEquals(Appphoto expected, Appphoto actual) {
        assertThat(actual)
            .as("Verify Appphoto relevant properties")
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getImage()).as("check image").isEqualTo(expected.getImage()))
            .satisfies(a -> assertThat(a.getImageContentType()).as("check image content type").isEqualTo(expected.getImageContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppphotoUpdatableRelationshipsEquals(Appphoto expected, Appphoto actual) {
        assertThat(actual)
            .as("Verify Appphoto relationships")
            .satisfies(a -> assertThat(a.getAppuser()).as("check appuser").isEqualTo(expected.getAppuser()));
    }
}
