package com.opencode.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppuserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppuserAllPropertiesEquals(Appuser expected, Appuser actual) {
        assertAppuserAutoGeneratedPropertiesEquals(expected, actual);
        assertAppuserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppuserAllUpdatablePropertiesEquals(Appuser expected, Appuser actual) {
        assertAppuserUpdatableFieldsEquals(expected, actual);
        assertAppuserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppuserAutoGeneratedPropertiesEquals(Appuser expected, Appuser actual) {
        assertThat(actual)
            .as("Verify Appuser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppuserUpdatableFieldsEquals(Appuser expected, Appuser actual) {
        assertThat(actual)
            .as("Verify Appuser relevant properties")
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getBio()).as("check bio").isEqualTo(expected.getBio()))
            .satisfies(a -> assertThat(a.getFacebook()).as("check facebook").isEqualTo(expected.getFacebook()))
            .satisfies(a -> assertThat(a.getTwitter()).as("check twitter").isEqualTo(expected.getTwitter()))
            .satisfies(a -> assertThat(a.getLinkedin()).as("check linkedin").isEqualTo(expected.getLinkedin()))
            .satisfies(a -> assertThat(a.getInstagram()).as("check instagram").isEqualTo(expected.getInstagram()))
            .satisfies(a -> assertThat(a.getBirthdate()).as("check birthdate").isEqualTo(expected.getBirthdate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppuserUpdatableRelationshipsEquals(Appuser expected, Appuser actual) {
        assertThat(actual)
            .as("Verify Appuser relationships")
            .satisfies(a -> assertThat(a.getInterests()).as("check interests").isEqualTo(expected.getInterests()))
            .satisfies(a -> assertThat(a.getActivities()).as("check activities").isEqualTo(expected.getActivities()))
            .satisfies(a -> assertThat(a.getCelebs()).as("check celebs").isEqualTo(expected.getCelebs()));
    }
}
