package com.opencode.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BlockuserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockuserAllPropertiesEquals(Blockuser expected, Blockuser actual) {
        assertBlockuserAutoGeneratedPropertiesEquals(expected, actual);
        assertBlockuserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockuserAllUpdatablePropertiesEquals(Blockuser expected, Blockuser actual) {
        assertBlockuserUpdatableFieldsEquals(expected, actual);
        assertBlockuserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockuserAutoGeneratedPropertiesEquals(Blockuser expected, Blockuser actual) {
        assertThat(actual)
            .as("Verify Blockuser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockuserUpdatableFieldsEquals(Blockuser expected, Blockuser actual) {
        assertThat(actual)
            .as("Verify Blockuser relevant properties")
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockuserUpdatableRelationshipsEquals(Blockuser expected, Blockuser actual) {
        assertThat(actual)
            .as("Verify Blockuser relationships")
            .satisfies(a -> assertThat(a.getBlockeduser()).as("check blockeduser").isEqualTo(expected.getBlockeduser()))
            .satisfies(a -> assertThat(a.getBlockinguser()).as("check blockinguser").isEqualTo(expected.getBlockinguser()))
            .satisfies(a -> assertThat(a.getCblockeduser()).as("check cblockeduser").isEqualTo(expected.getCblockeduser()))
            .satisfies(a -> assertThat(a.getCblockinguser()).as("check cblockinguser").isEqualTo(expected.getCblockinguser()));
    }
}
