package com.opencode.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CcelebAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCcelebAllPropertiesEquals(Cceleb expected, Cceleb actual) {
        assertCcelebAutoGeneratedPropertiesEquals(expected, actual);
        assertCcelebAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCcelebAllUpdatablePropertiesEquals(Cceleb expected, Cceleb actual) {
        assertCcelebUpdatableFieldsEquals(expected, actual);
        assertCcelebUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCcelebAutoGeneratedPropertiesEquals(Cceleb expected, Cceleb actual) {
        assertThat(actual)
            .as("Verify Cceleb auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCcelebUpdatableFieldsEquals(Cceleb expected, Cceleb actual) {
        assertThat(actual)
            .as("Verify Cceleb relevant properties")
            .satisfies(a -> assertThat(a.getCelebName()).as("check celebName").isEqualTo(expected.getCelebName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCcelebUpdatableRelationshipsEquals(Cceleb expected, Cceleb actual) {
        assertThat(actual)
            .as("Verify Cceleb relationships")
            .satisfies(a -> assertThat(a.getCommunities()).as("check communities").isEqualTo(expected.getCommunities()));
    }
}
