package com.opencode.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CelebAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCelebAllPropertiesEquals(Celeb expected, Celeb actual) {
        assertCelebAutoGeneratedPropertiesEquals(expected, actual);
        assertCelebAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCelebAllUpdatablePropertiesEquals(Celeb expected, Celeb actual) {
        assertCelebUpdatableFieldsEquals(expected, actual);
        assertCelebUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCelebAutoGeneratedPropertiesEquals(Celeb expected, Celeb actual) {
        assertThat(actual)
            .as("Verify Celeb auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCelebUpdatableFieldsEquals(Celeb expected, Celeb actual) {
        assertThat(actual)
            .as("Verify Celeb relevant properties")
            .satisfies(a -> assertThat(a.getCelebName()).as("check celebName").isEqualTo(expected.getCelebName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCelebUpdatableRelationshipsEquals(Celeb expected, Celeb actual) {
        assertThat(actual)
            .as("Verify Celeb relationships")
            .satisfies(a -> assertThat(a.getAppusers()).as("check appusers").isEqualTo(expected.getAppusers()));
    }
}
