package com.opencode.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CinterestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCinterestAllPropertiesEquals(Cinterest expected, Cinterest actual) {
        assertCinterestAutoGeneratedPropertiesEquals(expected, actual);
        assertCinterestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCinterestAllUpdatablePropertiesEquals(Cinterest expected, Cinterest actual) {
        assertCinterestUpdatableFieldsEquals(expected, actual);
        assertCinterestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCinterestAutoGeneratedPropertiesEquals(Cinterest expected, Cinterest actual) {
        assertThat(actual)
            .as("Verify Cinterest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCinterestUpdatableFieldsEquals(Cinterest expected, Cinterest actual) {
        assertThat(actual)
            .as("Verify Cinterest relevant properties")
            .satisfies(a -> assertThat(a.getInterestName()).as("check interestName").isEqualTo(expected.getInterestName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCinterestUpdatableRelationshipsEquals(Cinterest expected, Cinterest actual) {
        assertThat(actual)
            .as("Verify Cinterest relationships")
            .satisfies(a -> assertThat(a.getCommunities()).as("check communities").isEqualTo(expected.getCommunities()));
    }
}
