package com.opencode.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommunityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityAllPropertiesEquals(Community expected, Community actual) {
        assertCommunityAutoGeneratedPropertiesEquals(expected, actual);
        assertCommunityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityAllUpdatablePropertiesEquals(Community expected, Community actual) {
        assertCommunityUpdatableFieldsEquals(expected, actual);
        assertCommunityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityAutoGeneratedPropertiesEquals(Community expected, Community actual) {
        assertThat(actual)
            .as("Verify Community auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityUpdatableFieldsEquals(Community expected, Community actual) {
        assertThat(actual)
            .as("Verify Community relevant properties")
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getCommunityName()).as("check communityName").isEqualTo(expected.getCommunityName()))
            .satisfies(a ->
                assertThat(a.getCommunityDescription()).as("check communityDescription").isEqualTo(expected.getCommunityDescription())
            )
            .satisfies(a -> assertThat(a.getImage()).as("check image").isEqualTo(expected.getImage()))
            .satisfies(a -> assertThat(a.getImageContentType()).as("check image content type").isEqualTo(expected.getImageContentType()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityUpdatableRelationshipsEquals(Community expected, Community actual) {
        assertThat(actual)
            .as("Verify Community relationships")
            .satisfies(a -> assertThat(a.getAppuser()).as("check appuser").isEqualTo(expected.getAppuser()))
            .satisfies(a -> assertThat(a.getCinterests()).as("check cinterests").isEqualTo(expected.getCinterests()))
            .satisfies(a -> assertThat(a.getCactivities()).as("check cactivities").isEqualTo(expected.getCactivities()))
            .satisfies(a -> assertThat(a.getCcelebs()).as("check ccelebs").isEqualTo(expected.getCcelebs()));
    }
}
