package com.opencode.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConfigVariablesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigVariablesAllPropertiesEquals(ConfigVariables expected, ConfigVariables actual) {
        assertConfigVariablesAutoGeneratedPropertiesEquals(expected, actual);
        assertConfigVariablesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigVariablesAllUpdatablePropertiesEquals(ConfigVariables expected, ConfigVariables actual) {
        assertConfigVariablesUpdatableFieldsEquals(expected, actual);
        assertConfigVariablesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigVariablesAutoGeneratedPropertiesEquals(ConfigVariables expected, ConfigVariables actual) {
        assertThat(actual)
            .as("Verify ConfigVariables auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigVariablesUpdatableFieldsEquals(ConfigVariables expected, ConfigVariables actual) {
        assertThat(actual)
            .as("Verify ConfigVariables relevant properties")
            .satisfies(a -> assertThat(a.getConfigVarLong1()).as("check configVarLong1").isEqualTo(expected.getConfigVarLong1()))
            .satisfies(a -> assertThat(a.getConfigVarLong2()).as("check configVarLong2").isEqualTo(expected.getConfigVarLong2()))
            .satisfies(a -> assertThat(a.getConfigVarLong3()).as("check configVarLong3").isEqualTo(expected.getConfigVarLong3()))
            .satisfies(a -> assertThat(a.getConfigVarLong4()).as("check configVarLong4").isEqualTo(expected.getConfigVarLong4()))
            .satisfies(a -> assertThat(a.getConfigVarLong5()).as("check configVarLong5").isEqualTo(expected.getConfigVarLong5()))
            .satisfies(a -> assertThat(a.getConfigVarLong6()).as("check configVarLong6").isEqualTo(expected.getConfigVarLong6()))
            .satisfies(a -> assertThat(a.getConfigVarLong7()).as("check configVarLong7").isEqualTo(expected.getConfigVarLong7()))
            .satisfies(a -> assertThat(a.getConfigVarLong8()).as("check configVarLong8").isEqualTo(expected.getConfigVarLong8()))
            .satisfies(a -> assertThat(a.getConfigVarLong9()).as("check configVarLong9").isEqualTo(expected.getConfigVarLong9()))
            .satisfies(a -> assertThat(a.getConfigVarLong10()).as("check configVarLong10").isEqualTo(expected.getConfigVarLong10()))
            .satisfies(a -> assertThat(a.getConfigVarLong11()).as("check configVarLong11").isEqualTo(expected.getConfigVarLong11()))
            .satisfies(a -> assertThat(a.getConfigVarLong12()).as("check configVarLong12").isEqualTo(expected.getConfigVarLong12()))
            .satisfies(a -> assertThat(a.getConfigVarLong13()).as("check configVarLong13").isEqualTo(expected.getConfigVarLong13()))
            .satisfies(a -> assertThat(a.getConfigVarLong14()).as("check configVarLong14").isEqualTo(expected.getConfigVarLong14()))
            .satisfies(a -> assertThat(a.getConfigVarLong15()).as("check configVarLong15").isEqualTo(expected.getConfigVarLong15()))
            .satisfies(a ->
                assertThat(a.getConfigVarBoolean16()).as("check configVarBoolean16").isEqualTo(expected.getConfigVarBoolean16())
            )
            .satisfies(a ->
                assertThat(a.getConfigVarBoolean17()).as("check configVarBoolean17").isEqualTo(expected.getConfigVarBoolean17())
            )
            .satisfies(a ->
                assertThat(a.getConfigVarBoolean18()).as("check configVarBoolean18").isEqualTo(expected.getConfigVarBoolean18())
            )
            .satisfies(a -> assertThat(a.getConfigVarString19()).as("check configVarString19").isEqualTo(expected.getConfigVarString19()))
            .satisfies(a -> assertThat(a.getConfigVarString20()).as("check configVarString20").isEqualTo(expected.getConfigVarString20()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigVariablesUpdatableRelationshipsEquals(ConfigVariables expected, ConfigVariables actual) {
        // empty method
    }
}
