package com.opencode.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FrontpageconfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrontpageconfigAllPropertiesEquals(Frontpageconfig expected, Frontpageconfig actual) {
        assertFrontpageconfigAutoGeneratedPropertiesEquals(expected, actual);
        assertFrontpageconfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrontpageconfigAllUpdatablePropertiesEquals(Frontpageconfig expected, Frontpageconfig actual) {
        assertFrontpageconfigUpdatableFieldsEquals(expected, actual);
        assertFrontpageconfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrontpageconfigAutoGeneratedPropertiesEquals(Frontpageconfig expected, Frontpageconfig actual) {
        assertThat(actual)
            .as("Verify Frontpageconfig auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrontpageconfigUpdatableFieldsEquals(Frontpageconfig expected, Frontpageconfig actual) {
        assertThat(actual)
            .as("Verify Frontpageconfig relevant properties")
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getTopNews1()).as("check topNews1").isEqualTo(expected.getTopNews1()))
            .satisfies(a -> assertThat(a.getTopNews2()).as("check topNews2").isEqualTo(expected.getTopNews2()))
            .satisfies(a -> assertThat(a.getTopNews3()).as("check topNews3").isEqualTo(expected.getTopNews3()))
            .satisfies(a -> assertThat(a.getTopNews4()).as("check topNews4").isEqualTo(expected.getTopNews4()))
            .satisfies(a -> assertThat(a.getTopNews5()).as("check topNews5").isEqualTo(expected.getTopNews5()))
            .satisfies(a -> assertThat(a.getLatestNews1()).as("check latestNews1").isEqualTo(expected.getLatestNews1()))
            .satisfies(a -> assertThat(a.getLatestNews2()).as("check latestNews2").isEqualTo(expected.getLatestNews2()))
            .satisfies(a -> assertThat(a.getLatestNews3()).as("check latestNews3").isEqualTo(expected.getLatestNews3()))
            .satisfies(a -> assertThat(a.getLatestNews4()).as("check latestNews4").isEqualTo(expected.getLatestNews4()))
            .satisfies(a -> assertThat(a.getLatestNews5()).as("check latestNews5").isEqualTo(expected.getLatestNews5()))
            .satisfies(a -> assertThat(a.getBreakingNews1()).as("check breakingNews1").isEqualTo(expected.getBreakingNews1()))
            .satisfies(a -> assertThat(a.getRecentPosts1()).as("check recentPosts1").isEqualTo(expected.getRecentPosts1()))
            .satisfies(a -> assertThat(a.getRecentPosts2()).as("check recentPosts2").isEqualTo(expected.getRecentPosts2()))
            .satisfies(a -> assertThat(a.getRecentPosts3()).as("check recentPosts3").isEqualTo(expected.getRecentPosts3()))
            .satisfies(a -> assertThat(a.getRecentPosts4()).as("check recentPosts4").isEqualTo(expected.getRecentPosts4()))
            .satisfies(a -> assertThat(a.getFeaturedArticles1()).as("check featuredArticles1").isEqualTo(expected.getFeaturedArticles1()))
            .satisfies(a -> assertThat(a.getFeaturedArticles2()).as("check featuredArticles2").isEqualTo(expected.getFeaturedArticles2()))
            .satisfies(a -> assertThat(a.getFeaturedArticles3()).as("check featuredArticles3").isEqualTo(expected.getFeaturedArticles3()))
            .satisfies(a -> assertThat(a.getFeaturedArticles4()).as("check featuredArticles4").isEqualTo(expected.getFeaturedArticles4()))
            .satisfies(a -> assertThat(a.getFeaturedArticles5()).as("check featuredArticles5").isEqualTo(expected.getFeaturedArticles5()))
            .satisfies(a -> assertThat(a.getFeaturedArticles6()).as("check featuredArticles6").isEqualTo(expected.getFeaturedArticles6()))
            .satisfies(a -> assertThat(a.getFeaturedArticles7()).as("check featuredArticles7").isEqualTo(expected.getFeaturedArticles7()))
            .satisfies(a -> assertThat(a.getFeaturedArticles8()).as("check featuredArticles8").isEqualTo(expected.getFeaturedArticles8()))
            .satisfies(a -> assertThat(a.getFeaturedArticles9()).as("check featuredArticles9").isEqualTo(expected.getFeaturedArticles9()))
            .satisfies(a ->
                assertThat(a.getFeaturedArticles10()).as("check featuredArticles10").isEqualTo(expected.getFeaturedArticles10())
            )
            .satisfies(a -> assertThat(a.getPopularNews1()).as("check popularNews1").isEqualTo(expected.getPopularNews1()))
            .satisfies(a -> assertThat(a.getPopularNews2()).as("check popularNews2").isEqualTo(expected.getPopularNews2()))
            .satisfies(a -> assertThat(a.getPopularNews3()).as("check popularNews3").isEqualTo(expected.getPopularNews3()))
            .satisfies(a -> assertThat(a.getPopularNews4()).as("check popularNews4").isEqualTo(expected.getPopularNews4()))
            .satisfies(a -> assertThat(a.getPopularNews5()).as("check popularNews5").isEqualTo(expected.getPopularNews5()))
            .satisfies(a -> assertThat(a.getPopularNews6()).as("check popularNews6").isEqualTo(expected.getPopularNews6()))
            .satisfies(a -> assertThat(a.getPopularNews7()).as("check popularNews7").isEqualTo(expected.getPopularNews7()))
            .satisfies(a -> assertThat(a.getPopularNews8()).as("check popularNews8").isEqualTo(expected.getPopularNews8()))
            .satisfies(a -> assertThat(a.getWeeklyNews1()).as("check weeklyNews1").isEqualTo(expected.getWeeklyNews1()))
            .satisfies(a -> assertThat(a.getWeeklyNews2()).as("check weeklyNews2").isEqualTo(expected.getWeeklyNews2()))
            .satisfies(a -> assertThat(a.getWeeklyNews3()).as("check weeklyNews3").isEqualTo(expected.getWeeklyNews3()))
            .satisfies(a -> assertThat(a.getWeeklyNews4()).as("check weeklyNews4").isEqualTo(expected.getWeeklyNews4()))
            .satisfies(a -> assertThat(a.getNewsFeeds1()).as("check newsFeeds1").isEqualTo(expected.getNewsFeeds1()))
            .satisfies(a -> assertThat(a.getNewsFeeds2()).as("check newsFeeds2").isEqualTo(expected.getNewsFeeds2()))
            .satisfies(a -> assertThat(a.getNewsFeeds3()).as("check newsFeeds3").isEqualTo(expected.getNewsFeeds3()))
            .satisfies(a -> assertThat(a.getNewsFeeds4()).as("check newsFeeds4").isEqualTo(expected.getNewsFeeds4()))
            .satisfies(a -> assertThat(a.getNewsFeeds5()).as("check newsFeeds5").isEqualTo(expected.getNewsFeeds5()))
            .satisfies(a -> assertThat(a.getNewsFeeds6()).as("check newsFeeds6").isEqualTo(expected.getNewsFeeds6()))
            .satisfies(a -> assertThat(a.getUsefulLinks1()).as("check usefulLinks1").isEqualTo(expected.getUsefulLinks1()))
            .satisfies(a -> assertThat(a.getUsefulLinks2()).as("check usefulLinks2").isEqualTo(expected.getUsefulLinks2()))
            .satisfies(a -> assertThat(a.getUsefulLinks3()).as("check usefulLinks3").isEqualTo(expected.getUsefulLinks3()))
            .satisfies(a -> assertThat(a.getUsefulLinks4()).as("check usefulLinks4").isEqualTo(expected.getUsefulLinks4()))
            .satisfies(a -> assertThat(a.getUsefulLinks5()).as("check usefulLinks5").isEqualTo(expected.getUsefulLinks5()))
            .satisfies(a -> assertThat(a.getUsefulLinks6()).as("check usefulLinks6").isEqualTo(expected.getUsefulLinks6()))
            .satisfies(a -> assertThat(a.getRecentVideos1()).as("check recentVideos1").isEqualTo(expected.getRecentVideos1()))
            .satisfies(a -> assertThat(a.getRecentVideos2()).as("check recentVideos2").isEqualTo(expected.getRecentVideos2()))
            .satisfies(a -> assertThat(a.getRecentVideos3()).as("check recentVideos3").isEqualTo(expected.getRecentVideos3()))
            .satisfies(a -> assertThat(a.getRecentVideos4()).as("check recentVideos4").isEqualTo(expected.getRecentVideos4()))
            .satisfies(a -> assertThat(a.getRecentVideos5()).as("check recentVideos5").isEqualTo(expected.getRecentVideos5()))
            .satisfies(a -> assertThat(a.getRecentVideos6()).as("check recentVideos6").isEqualTo(expected.getRecentVideos6()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrontpageconfigUpdatableRelationshipsEquals(Frontpageconfig expected, Frontpageconfig actual) {
        // empty method
    }
}
