package com.opencode.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InterestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterestAllPropertiesEquals(Interest expected, Interest actual) {
        assertInterestAutoGeneratedPropertiesEquals(expected, actual);
        assertInterestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterestAllUpdatablePropertiesEquals(Interest expected, Interest actual) {
        assertInterestUpdatableFieldsEquals(expected, actual);
        assertInterestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterestAutoGeneratedPropertiesEquals(Interest expected, Interest actual) {
        assertThat(actual)
            .as("Verify Interest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterestUpdatableFieldsEquals(Interest expected, Interest actual) {
        assertThat(actual)
            .as("Verify Interest relevant properties")
            .satisfies(a -> assertThat(a.getInterestName()).as("check interestName").isEqualTo(expected.getInterestName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInterestUpdatableRelationshipsEquals(Interest expected, Interest actual) {
        assertThat(actual)
            .as("Verify Interest relationships")
            .satisfies(a -> assertThat(a.getAppusers()).as("check appusers").isEqualTo(expected.getAppusers()));
    }
}
