package com.opencode.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PostAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostAllPropertiesEquals(Post expected, Post actual) {
        assertPostAutoGeneratedPropertiesEquals(expected, actual);
        assertPostAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostAllUpdatablePropertiesEquals(Post expected, Post actual) {
        assertPostUpdatableFieldsEquals(expected, actual);
        assertPostUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostAutoGeneratedPropertiesEquals(Post expected, Post actual) {
        assertThat(actual)
            .as("Verify Post auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostUpdatableFieldsEquals(Post expected, Post actual) {
        assertThat(actual)
            .as("Verify Post relevant properties")
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getPublicationDate()).as("check publicationDate").isEqualTo(expected.getPublicationDate()))
            .satisfies(a -> assertThat(a.getHeadline()).as("check headline").isEqualTo(expected.getHeadline()))
            .satisfies(a -> assertThat(a.getLeadtext()).as("check leadtext").isEqualTo(expected.getLeadtext()))
            .satisfies(a -> assertThat(a.getBodytext()).as("check bodytext").isEqualTo(expected.getBodytext()))
            .satisfies(a -> assertThat(a.getQuote()).as("check quote").isEqualTo(expected.getQuote()))
            .satisfies(a -> assertThat(a.getConclusion()).as("check conclusion").isEqualTo(expected.getConclusion()))
            .satisfies(a -> assertThat(a.getLinkText()).as("check linkText").isEqualTo(expected.getLinkText()))
            .satisfies(a -> assertThat(a.getLinkURL()).as("check linkURL").isEqualTo(expected.getLinkURL()))
            .satisfies(a -> assertThat(a.getImage()).as("check image").isEqualTo(expected.getImage()))
            .satisfies(a -> assertThat(a.getImageContentType()).as("check image content type").isEqualTo(expected.getImageContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostUpdatableRelationshipsEquals(Post expected, Post actual) {
        assertThat(actual)
            .as("Verify Post relationships")
            .satisfies(a -> assertThat(a.getAppuser()).as("check appuser").isEqualTo(expected.getAppuser()))
            .satisfies(a -> assertThat(a.getBlog()).as("check blog").isEqualTo(expected.getBlog()))
            .satisfies(a -> assertThat(a.getTags()).as("check tags").isEqualTo(expected.getTags()))
            .satisfies(a -> assertThat(a.getTopics()).as("check topics").isEqualTo(expected.getTopics()));
    }
}
