package com.opencode.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UrllinkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUrllinkAllPropertiesEquals(Urllink expected, Urllink actual) {
        assertUrllinkAutoGeneratedPropertiesEquals(expected, actual);
        assertUrllinkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUrllinkAllUpdatablePropertiesEquals(Urllink expected, Urllink actual) {
        assertUrllinkUpdatableFieldsEquals(expected, actual);
        assertUrllinkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUrllinkAutoGeneratedPropertiesEquals(Urllink expected, Urllink actual) {
        assertThat(actual)
            .as("Verify Urllink auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUrllinkUpdatableFieldsEquals(Urllink expected, Urllink actual) {
        assertThat(actual)
            .as("Verify Urllink relevant properties")
            .satisfies(a -> assertThat(a.getLinkText()).as("check linkText").isEqualTo(expected.getLinkText()))
            .satisfies(a -> assertThat(a.getLinkURL()).as("check linkURL").isEqualTo(expected.getLinkURL()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUrllinkUpdatableRelationshipsEquals(Urllink expected, Urllink actual) {
        // empty method
    }
}
